#  This is Production Code : 
This is not good approch we have to do so many things repeatively 

In [13]:
import pickle
import numpy as np

## load all three file here

In [19]:
ohe_sex = pickle.load(open('Model/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('Model/ohe_embarked.pkl','rb'))
clf = pickle.load(open('Model/clf.pkl','rb'))

ohe_sex

OneHotEncoder(drop='first', handle_unknown='ignore', sparse=False)

 ## Creating new input 

In [15]:
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype = object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [16]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

C:\python3.9.7\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1.]])

In [18]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

C:\python3.9.7\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 0.]])

In [22]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_age

array([[31.0]], dtype=object)

In [23]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [24]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 1.0, 0.0, 0.0, 1.0, 0.0]], dtype=object)

In [25]:
clf.predict(test_input_transformed)

array([1], dtype=int64)