## PipeLine 
**Pipelines chains together multiple steps so that the output of each step is used as input to the next step.**

**Pipelines makes it easy to apply the same preprocessing to train and test.**

In [24]:
# Without Pipeline

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("ttrain.csv")
df.sample(4)

PassengerId  Survived  Pclass  \
528          529         0       3   
507          508         1       1   
717          718         1       2   
442          443         0       3   

                                              Name     Sex   Age  SibSp  \
528                      Salonen, Mr. Johan Werner    male  39.0      0   
507  Bradley, Mr. George ("George Arthur Brayton")    male   NaN      0   
717            Troutt, Miss. Edwina Celia "Winnie"  female  27.0      0   
442                      Petterson, Mr. Johan Emil    male  25.0      1   

     Parch   Ticket    Fare Cabin Embarked  
528      0  3101296   7.925   NaN        S  
507      0   111427  26.550   NaN        S  
717      0    34218  10.500  E101        S  
442      0   347076   7.775   NaN        S

In [3]:
# we dont find this column helpfull so we are dropping it 
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [4]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

### Step 1 : Split data 

In [5]:
X_train, x_test , y_train, y_test = train_test_split(df.drop(columns=['Survived']),
                                                    df['Survived'],test_size=0.2,random_state=42)

In [6]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

## Missing value : Imputer  

In [7]:
sa = SimpleImputer()
x1= sa.fit_transform(X_train[['Age']])
y1 = sa.transform(x_test[['Age']])

se = SimpleImputer(strategy= 'most_frequent')
x2=   se.fit_transform(X_train[['Embarked']])
y2 = se.transform(x_test[['Embarked']])

x1
x2

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

## One Hot Encoding 

In [8]:
ohe_sex = OneHotEncoder(sparse=False,drop='first',handle_unknown='ignore') #if found new value in future ignore it 
x_train_sex= ohe_sex.fit_transform(X_train[['Sex']])
x_test_sex= ohe_sex.transform(x_test[['Sex']])


ohe_embarked = OneHotEncoder(sparse=False,handle_unknown='ignore')
x_train_emb = ohe_embarked.fit_transform(X_train[['Embarked']])
x_test_emb = ohe_embarked.transform(x_test[['Embarked']])

In [9]:
x_train_sex
x_test_emb 

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],


## Concatenate 

In [10]:
X_train_remening = X_train.drop(columns = ['Sex','Embarked','Age'])
X_test_remening  = x_test.drop(columns = ['Sex','Embarked','Age'] )

In [11]:
X_train_transformed = np.concatenate((X_train_remening,x_train_emb,x_train_sex,x1),axis=1)
X_train_transformed

array([[ 1. ,  0. ,  0. , ...,  0. ,  1. , 45.5],
       [ 2. ,  0. ,  0. , ...,  0. ,  1. , 23. ],
       [ 3. ,  0. ,  0. , ...,  0. ,  1. , 32. ],
       ...,
       [ 3. ,  2. ,  0. , ...,  0. ,  1. , 41. ],
       [ 1. ,  1. ,  2. , ...,  0. ,  0. , 14. ],
       [ 1. ,  0. ,  1. , ...,  0. ,  1. , 21. ]])

In [12]:
x_test_transformed = np.concatenate((X_test_remening,x_test_emb,x_test_sex,y1),axis=1)

## Model_training 

In [13]:
clf =DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)


DecisionTreeClassifier()

In [14]:
y_pred =clf.predict(x_test_transformed)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7877094972067039

## Deploy into Website

In [17]:
import pickle

In [23]:
pickle.dump(ohe_sex,open('Model/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('Model/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('Model/clf.pkl','wb')) 


#you cannot see this files 